-- Geração de Modelo físico
-- Sql ANSI 2003 - brModelo.


-- criada
CREATE TABLE PESSOAS (
PES_ID number (5) PRIMARY KEY NOT NULL,
PES_FONE varchar2 (11) NOT NULL,
PES_NOME vachar2 (50) NOT NULL,
LOG_ID number (5) NOT NULL

);
-- criada
CREATE TABLE FUNCIONARIOS (
FUN_SALARIO number (7,2) NOT NULL,
FUN_CARGO varchar2 (30) NOT NULL,
PF_CPF char (14) NOT NULL,
PF_DT_NASC date,
FUN_PES_ID number (5) PRIMARY KEY,
FOREIGN KEY(FUN_PES_ID) REFERENCES PESSOAS (PES_ID)
);
-- criada
CREATE TABLE CLIENTES (
CLI_NUM_CART varchar2 (20),
PF_CPF char (14) NOT NULL,
PF_DT_NASC date NOT NULL,
CLI_PES_ID number (5) PRIMARY KEY NOT NULL,
CON_ID number (5) NOT NULL,
FOREIGN KEY(CLI_PES_ID) REFERENCES PESSOAS (PES_ID)
);
-- CRIADA

	CREATE TABLE FORNECEDOR (
	FOR_DT_CADASTRO date NOT NULL,
	FOR_SITUACAO varchar2 (20) NOT NULL,
	FOR_CNPJ char (14) NOT NULL,
	FOR_PES_ID number (5) PRIMARY KEY NOT NULL,
	FOREIGN KEY(FOR_PES_ID) REFERENCES PESSOAS (PES_ID)
	);
	
-- CRIADA
CREATE TABLE POSSUI (
PRO_ID number (5) not null,
COM_ID number (5) not null,
PRIMARY KEY(PRO_ID,COM_ID)
);

-- criada
CREATE TABLE PRODUTOS (
PRO_DT_FABRI date NOT NULL,
PROD_DT_VALID date NOT NULL,
PRO_ID number (5) PRIMARY KEY NOT NULL,
PRO_VALOR number (7,2) NOT NULL,
PRO_TIPO varchar2 (30) NOT NULL,
PRO_NOME varchar2 (50) NOT NULL
);
-- criada
CREATE TABLE LOGRADOURO (
LOG_RUA varchar2 (50) NOT NULL,
LOG_CEP varchar2 (8) NOT NULL,
LOG_BAIRRO varchar2 (30) NOT NULL,
LOG_CIDADE varchar2 (30) NOT NULL,
LOG_UF char (2) NOT NULL,
LOG_ID number (5) PRIMARY KEY NOT NULL,
LOG_NUM number (5) 
);
-- CRIADA
CREATE TABLE ATENDIMENTO (
ATE_COM_ID number (5) NOT NULL,
ATE_FUN_PES_ID number (5) NOT NULL,
ATE_CLI_PES_ID number (5) NOT NULL,
PRIMARY KEY(ATE_COM_ID,ATE_FUN_PES_ID,ATE_CLI_PES_ID),
FOREIGN KEY(ATE_FUN_PES_ID) REFERENCES FUNCIONARIOS (FUN_PES_ID),
FOREIGN KEY(ATE_CLI_PES_ID) REFERENCES CLIENTES (CLI_PES_ID)
);
-- criada
CREATE TABLE COMPRAS (
COM_ID number (5) PRIMARY KEY NOT NULL,
COM_VALOR_TOTAL number (7,2) NOT NULL,
COM_DATA date NOT NULL,
COM_FORMA_PAG varchar2 (11) NOT NULL
);
-- criada
CREATE TABLE CONVENIOS (
CON_ID number (5) PRIMARY KEY NOT NULL,
CON_NOME varchar2 (50) NOT NULL
);
--CRIADA
CREATE TABLE FORNECE (
FNC_DT date NOT NULL,
FNC_PRO_ID number (5) NOT NULL,
FNC_FOR_PES_ID number (5) NOT NULL,
FNC_QUANT number(4) NOT NULL,
FNC_VALOR number (7,2) NOT NULL,
PRIMARY KEY(FNC_PRO_ID,FNC_FOR_PES_ID),
FOREIGN KEY(FNC_PRO_ID) REFERENCES PRODUTOS (PRO_ID),
FOREIGN KEY(FNC_FOR_PES_ID) REFERENCES FORNECEDOR (FOR_PES_ID)
);
-- FEITO
ALTER TABLE PESSOAS ADD FOREIGN KEY(LOG_ID) REFERENCES LOGRADOURO (LOG_ID);
ALTER TABLE CLIENTES ADD FOREIGN KEY(CON_ID) REFERENCES CONVENIOS (CON_ID);
ALTER TABLE POSSUI ADD FOREIGN KEY(PRO_ID) REFERENCES PRODUTOS (PRO_ID);
ALTER TABLE POSSUI ADD FOREIGN KEY(COM_ID) REFERENCES COMPRAS (COM_ID);
ALTER TABLE ATENDIMENTO ADD FOREIGN KEY(ATE_COM_ID) REFERENCES COMPRAS (COM_ID);
